from pydantic import BaseModel
from typing import List, Optional
from datetime import datetime
from uuid import UUID, uuid4

class SessionBase(BaseModel):
    host_name: str
    location: str
    scheduled_time: Optional[datetime] = None

class SessionCreate(SessionBase):
    pass

class SessionResponse(SessionBase):
    id: UUID
    status: str
    created_at: datetime
    expires_at: datetime
    invite_link: str
    booking_status: str = "none"
    booking_reference: Optional[str] = None
    booking_message: Optional[str] = None

class ParticipantBase(BaseModel):
    name: str
    dietary_restrictions: Optional[str] = None
    cuisine_preferences: Optional[str] = None
    budget_tier: Optional[str] = None
    vibe: Optional[str] = None

class ParticipantCreate(ParticipantBase):
    pass

class ParticipantResponse(ParticipantBase):
    id: UUID
    session_id: UUID
    is_host: bool

class VoteCreate(BaseModel):
    participant_id: UUID
    venue_id: str
    score: int

class ConflictAnalysis(BaseModel):
    has_conflicts: bool = False
    conflicts: List[str] = []
    resolution: str = ""

class Recommendation(BaseModel):
    id: Optional[str] = None # Generated by DB
    business_id: str
    name: str
    rating: float
    price: Optional[str] = "$$"  # Default if not provided
    image_url: Optional[str] = None
    ai_reasoning: Optional[str] = "Recommended based on your preferences."
    categories: List[str] = []  # Default to empty list
    score: int = 0
    vote_count: int = 0
    why_picked: str = ""
    trade_offs: List[str] = []

